# Build & Test
# Versions: .NET Core 3.1.x, 5.0.x
# Trigger: pull request, push
# actions/checkout@v2 and actions/setup-dotnet@v1 are community actions that will get your code and setup dotnet

name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
        
    - name: Install dependencies
      run: dotnet restore ./src/
      
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./src/
